services:
  nginx:
    image: nginx:alpine
    container_name: mudskipper_nginx
    ports:
      # Exposes the NGINX listening port on your localhost 8080
      - "8080:80"
    volumes:
      # Mount the configuration we wrote
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount the Mudskipper directory so NGINX can access /project/ files
      - ./:/workspace
    extra_hosts:
      # Allow the docker container to route to localhost:8000 on the host mac
      - "host.docker.internal:host-gateway"
